language: python

os:
    - linux
    - osx

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

before_install:
    - pip install Cython

install:
    - pip install .
    - python setup.py build_ext --inplace

script:
    - nosetests --with-doctest

notifications:
    email: false
